apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
 components:
   ingressGateways:
   - name: istio-ingressgateway1
     enabled: true
     k8s:
       service:
         type: LoadBalancer
         loadBalancerIP: $STATIC_IP1
         ports:
         - name: status-port
           port: 15021 # for ASM 1.7.x and above, else 15020
           targetPort: 15021 # for ASM 1.7.x and above, else 15020
         - name: http2
           port: 80
           targetPort: 8080
         - name: https
           port: 443
           targetPort: 8443

   - name: istio-ingressgateway2
     enabled: true
     k8s:
       service:
         type: LoadBalancer
         loadBalancerIP:  $STATIC_IP2
         ports:
         - name: status-port
           port: 15021 # for ASM 1.7.x and above, else 15020
           targetPort: 15021 # for ASM 1.7.x and above, else 15020
         - name: http2
           port: 80
           targetPort: 8080
         - name: https
           port: 443
           targetPort: 8443

